# Generated by Django 4.2.16 on 2024-10-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
